language: cpp
sudo: required
script:
  - sudo apt install g++
  - sudo apt install libwxgtk3.0-gtk3-dev 
  - gcc --version
  - g++ *.cpp `wx-config --cxxflags --libs`
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
