language: cpp
sudo: required
script:
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
  - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++
  - sudo apt install libwxgtk3.0-gtk3-dev
  - gcc --version
  - g++ *.cpp `wx-config --cxxflags --libs`

addons:
  apt:
    sources:
    - ubuntu-latest
